# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: MIT

name: Release

on:
  push:
    tags:
    - '*'

permissions:
  contents: read

jobs:
  create_release:
    runs-on: ubuntu-24.04
    name: Create release on GitHub
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - env:
        VERSION: ${{ github.ref_name }}
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create "$VERSION" --verify-tag --generate-notes
