# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: MIT

name: Release

on:
  push:
    tags:
    - '*'

permissions:
  contents: read

jobs:
  create_release:
    runs-on: ubuntu-24.04
    name: Create release on GitHub
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - env:
        VERSION: ${{ github.ref_name }}
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create "$VERSION" --verify-tag --generate-notes
